name: one_context
description: OneContext provides a simple way to deal with Dialogs, Overlays, Navigations, Theme* and MediaQuery* with no need of BuildContext.
version: 3.0.0-rc-1
homepage: https://github.com/emanuel-braz/one_context
repository: https://github.com/emanuel-braz/one_context.git

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.2
  back_button_interceptor: ^8.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pana: ^0.22.18
    
flutter:
